In [1]:
#OpenCV Mini Project - Rotation Effect on live Webcam Feed
import cv2
import matplotlib.pyplot as plt
import numpy as np
import time

def main():
    imgpath="C:\\Users\\DELL\\Desktop\\Machine Learning A-Z Template Folder\\standard_test_images\\"
    
    imgpath1=imgpath+"cup.tiff"
    
    img=cv2.imread(imgpath1,1)
   
    
    rows,column,channel=img.shape
    angle = 360
    while True:
        if angle==0:
            angle=360
            
        R=cv2.getRotationMatrix2D((column/2,rows/2),angle,0.5)
        print(R)
    
        output=cv2.warpAffine(img,R,(column,rows))
    
        cv2.imshow('Rotated Image', output)
        angle=angle-1
        time.sleep(0.01)
        
        if cv2.waitKey(1) == 27:
            break
        
        
    cv2.destroyWindow('rotated image')
    
if __name__=='__main__':
    main()

[[ 5.0000000e-01 -1.2246468e-16  1.2800000e+02]
 [ 1.2246468e-16  5.0000000e-01  1.2800000e+02]]
[[ 4.99923848e-01 -8.72620322e-03  1.30253403e+02]
 [ 8.72620322e-03  4.99923848e-01  1.25785587e+02]]
[[ 4.99695414e-01 -1.74497484e-02  1.32545110e+02]
 [ 1.74497484e-02  4.99695414e-01  1.23610839e+02]]
[[ 4.99314767e-01 -2.61679781e-02  1.34874422e+02]
 [ 2.61679781e-02  4.99314767e-01  1.21476417e+02]]
[[ 4.98782025e-01 -3.48782369e-02  1.37240630e+02]
 [ 3.48782369e-02  4.98782025e-01  1.19382973e+02]]
[[ 4.98097349e-01 -4.35778714e-02  1.39643014e+02]
 [ 4.35778714e-02  4.98097349e-01  1.17331144e+02]]
[[ 4.97260948e-01 -5.22642316e-02  1.42080841e+02]
 [ 5.22642316e-02  4.97260948e-01  1.15321554e+02]]
[[ 4.96273076e-01 -6.09346717e-02  1.44553369e+02]
 [ 6.09346717e-02  4.96273076e-01  1.13354817e+02]]
[[ 4.95134034e-01 -6.95865505e-02  1.47059844e+02]
 [ 6.95865505e-02  4.95134034e-01  1.11431530e+02]]
[[ 4.93844170e-01 -7.82172325e-02  1.49599504e+02]
 [ 7.82172325e-02  4.9384417

[[ 3.48782369e-02 -4.98782025e-01  3.74759370e+02]
 [ 4.98782025e-01  3.48782369e-02  1.19382973e+02]]
[[ 2.61679781e-02 -4.99314767e-01  3.77125578e+02]
 [ 4.99314767e-01  2.61679781e-02  1.21476417e+02]]
[[ 1.74497484e-02 -4.99695414e-01  3.79454890e+02]
 [ 4.99695414e-01  1.74497484e-02  1.23610839e+02]]
[[ 8.72620322e-03 -4.99923848e-01  3.81746597e+02]
 [ 4.99923848e-01  8.72620322e-03  1.25785587e+02]]
[[-9.18485099e-17 -5.00000000e-01  3.84000000e+02]
 [ 5.00000000e-01 -9.18485099e-17  1.28000000e+02]]
[[-8.72620322e-03 -4.99923848e-01  3.86214413e+02]
 [ 4.99923848e-01 -8.72620322e-03  1.30253403e+02]]
[[-1.74497484e-02 -4.99695414e-01  3.88389161e+02]
 [ 4.99695414e-01 -1.74497484e-02  1.32545110e+02]]
[[-2.61679781e-02 -4.99314767e-01  3.90523583e+02]
 [ 4.99314767e-01 -2.61679781e-02  1.34874422e+02]]
[[-3.48782369e-02 -4.98782025e-01  3.92617027e+02]
 [ 4.98782025e-01 -3.48782369e-02  1.37240630e+02]]
[[-4.35778714e-02 -4.98097349e-01  3.94668856e+02]
 [ 4.98097349e-01 -4.3

[[-4.89073800e-01 -1.03955845e-01  4.07815589e+02]
 [ 1.03955845e-01 -4.89073800e-01  3.54590196e+02]]
[[-4.90813592e-01 -9.54044977e-02  4.06071831e+02]
 [ 9.54044977e-02 -4.90813592e-01  3.57224728e+02]]
[[-4.92403877e-01 -8.68240888e-02  4.04282359e+02]
 [ 8.68240888e-02 -4.92403877e-01  3.59828426e+02]]
[[-4.93844170e-01 -7.82172325e-02  4.02447719e+02]
 [ 7.82172325e-02 -4.93844170e-01  3.62400496e+02]]
[[-4.95134034e-01 -6.95865505e-02  4.00568470e+02]
 [ 6.95865505e-02 -4.95134034e-01  3.64940156e+02]]
[[-4.96273076e-01 -6.09346717e-02  3.98645183e+02]
 [ 6.09346717e-02 -4.96273076e-01  3.67446631e+02]]
[[-4.97260948e-01 -5.22642316e-02  3.96678446e+02]
 [ 5.22642316e-02 -4.97260948e-01  3.69919159e+02]]
[[-4.98097349e-01 -4.35778714e-02  3.94668856e+02]
 [ 4.35778714e-02 -4.98097349e-01  3.72356986e+02]]
[[-4.98782025e-01 -3.48782369e-02  3.92617027e+02]
 [ 3.48782369e-02 -4.98782025e-01  3.74759370e+02]]
[[-4.99314767e-01 -2.61679781e-02  3.90523583e+02]
 [ 2.61679781e-02 -4.9